import = [
    "~/.config/alacritty/themes/monokai_charcoal.toml"
]

[cursor]
style = "Beam"
unfocused_hollow = false

[env]
TERM = "xterm"

[font]
size = 10

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"
