#!/bin/bash

ip -o -br addr | awk '{print $1, $3}' | cut -d "/" -f1 | while read line
do
  IFACE=$(echo $line | cut -d " " -f1)
  IP=$(echo $line | cut -d " " -f2)
  echo "$IFACE: http://$IP:8000/$1"
done

echo ""
echo "python server started..."
python3 -m http.server
