#!/usr/bin/env bash

RED='\033[0;31m'
BLUE='\033[0;34m'
Green='\033[0;32m'
NC='\033[0m'

if command -v apt &> /dev/null
then
  echo -e "${BLUE} [+] ${NC} apt found"
  echo -e "${BLUE} [+] ${NC} updating packages using apt..."
  sudo apt update -y &> /dev/null
  sudo apt full-upgrade -y &> /dev/null
  echo -e "${GREEN} ==>  apt update completed! ${NC}"
  echo -e "${BLUE} [+] ${NC} removing useless packages..."
  sudo apt autoremove &> /dev/null
  sudo apt autoclean -y &> /dev/null
  echo -e "${GREEN} ==>  apt cleaning completed! ${NC}"
fi

if command -v yay &> /dev/null
then
  echo -e "${BLUE} [+] ${NC} yay found"
  echo -e "${BLUE} [+] ${NC} updating packages using yay..."
  yay -Syyyu &>/dev/null
  echo -e "${GREEN} ==>  yay update completed! ${NC}"
  echo -e "${BLUE} [+] ${NC} cleaning unneeded dependencies"
  yay -Yc
  echo -e "${GREEN} ==>  yay cleaning completed ${NC}"
fi
