#!/bin/bash
grep "$1" << EOF

#nmap
nmap -sV -A -T4 --script=vuln -oN nmap.txt --min-rate 10000 -vvv 
sudo nmap -sU -sC -oN nmapUDP.txt --min-rate 10000 -vvv 
nmap -p- -sV -T3 --min-rate 10000 -oN nmapAllPorts.txt -vvv 

#directory busting
ffuf -w /usr/share/seclists/Discovery/Web-Contents/common.txt -ac  -u 

# stable shell
python3 -c "import pty;pty.spawn('/bin/bash');"
export TERM=xterm
stty raw -echo; fg

EOF
