#!/usr/bin/env bash

RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

# apt
if command -v apt &> /dev/null
then
  echo ""
  echo -e "${BLUE} [+] apt found ${NC}"
  echo -e "${BLUE} [+] updating packages using apt... ${NC}"
  sudo apt update -y 
  sudo apt full-upgrade -y
  echo -e "${RED} ==>  apt update completed! ${NC}"
  echo -e "${BLUE} [+] removing useless packages... ${NC}"
  sudo apt autoremove -y
  sudo apt autoclean -y
  echo -e "${RED} ==>  apt cleaning completed! ${NC}"
  echo ""
fi

# pacman
if command -v pacman &> /dev/null
then
  echo ""
  echo -e "${BLUE} [+] pacman found ${NC}"
  echo -e "${BLUE} [+] updating packages using pacman... ${NC}"
  sudo pacman -Syyyu --noconfirm
  echo -e "${RED} ==>  pacman update completed! ${NC}"
  echo -e "${BLUE} [+] cleaning unneeded dependencies ${NC}"
  sudo pacman -Sc --noconfirm
  echo -e "${RED} ==>  pacman cleaning completed ${NC}"
  echo ""
fi

# yay
if command -v yay &> /dev/null
then
  echo ""
  echo -e "${BLUE} [+] yay found ${NC}"
  echo -e "${BLUE} [+] updating packages using yay... ${NC}"
  yay -Syyyu --noconfirm
  echo -e "${RED} ==>  yay update completed! ${NC}"
  echo -e "${BLUE} [+] cleaning unneeded dependencies ${NC}"
  yay -Yc --noconfirm
  yay -Sc --noconfirm
  echo -e "${RED} ==>  yay cleaning completed ${NC}"
  echo ""
fi

# snap
if command -v snap &> /dev/null
then
  echo ""
  echo -e "${BLUE} [+] snap found ${NC}"
  echo -e "${BLUE} [+] refreshing snap ${NC}"
  sudo snap refresh
  echo -e "${RED} ==> snap refresh completed ${NC}"
  echo ""
fi

# flatpak
if command -v flatpak &> /dev/null
then
  echo ""
  echo -e "${BLUE} [+] flatpak found ${NC}"
  echo -e "${BLUE} [+] updating packages using flatpak ${NC}"
  flatpak update
  echo -e "${RED} ==> flatpak update completed ${NC}"
  echo -e "${BLUE} [+] repairing flatpak ${NC}"
  flatpak repair
  echo -e "${RED} ==> flatpak repair completed ${NC}"
  echo ""
fi
